### ISSUE TITLE
No compatible BlueSCSI device Found 

### ISSUE THREAD

**Issue by rjplaisted** [erichelgeson/BlueSCSI-Toolbox#11]
I've successfully flashed my BlueSCSC, but when I boot from my 6.0.8 image, open beta1, and run the Transfer app, I get the error that no compatible BlueSCSI device is found. I have a shared folder set up. I am trying this on my Mac Plus. Do you no what the issue could be?

**Comment by erichelgeson** [comment]
Could you verify the version number in LOG.txt on the SD card to ensure it did take the updated firmware?

**Comment by rjplaisted** [comment]
The version number from the log is 1.1-20221203-USB. Is that the correct version after flash?

**Comment by erichelgeson** [comment]
It is not, you will need to flash the bin in this https://github.com/erichelgeson/BlueSCSI-Toolbox#prepare-your-bluescsi - the version should have XFER BETA in it I believe (not near a bluescsi at the moment)

**Comment by erichelgeson** [comment]
Great! I do hope to roll this into the main release in the coming weeks, just been busy!
