### ISSUE TITLE
Can't find HD1-Beta.hda anywhere

### ISSUE THREAD

**Issue by SuperIlu** [erichelgeson/BlueSCSI-Toolbox#14]
Hi,

I'm sure I miss something here, but I can't find the mentioned `HD1-Beta.hda` with the Toolbox software anywhere.
Neither in this repo, nor in https://github.com/BlueSCSI/BlueSCSI-v2 and https://github.com/erichelgeson/BlueSCSI

**Comment by erichelgeson** [comment]
Hey sorry! I pulled the beta's as I'm prepping for the final release. (i thought i edited the releases to say that, i did not, doing so now)

**Comment by jacobpretorius** [comment]
@erichelgeson any update on the release? Or can you upload the beta.hda here or something in the meantime? Trying to use _any_ version of the toolbox software to move files at the moment.

**Comment by rampa069** [comment]
sorry opened another one because this one is closed..... closing the other.

**Comment by joelricci** [comment]
Also looking for `HD1-Beta.hda` for v1 hardware. Tried the image for v2 but it doesn't seem to work for v1.
