### ISSUE TITLE
Shows 13 filenames correctly, rest gibberish

### ISSUE THREAD

**Issue by renekint** [erichelgeson/BlueSCSI-Toolbox#16]
Hi,

I have a quite large 'shared' folder. When I open the SD Card reader on my Macintosh (Quadra 660AV, system 7.5.3, Open Transport 1.3) I see 13 filenames correctly (and exactly 13). The rest of the filenames are just little squares.

The files themselves seem unsorted - at least I have not found out yet which filenames are shown and which are not - so I do not know yet how it 'chooses' these filenames.

I have deleted some files to see if it was filename-related (e.g. no spaces), but that didn't give me any clue. The number of 13 files seems consistent. 

I am eager to know if this 'feature' can be reproduced by others ;-)

**Comment by erichelgeson** [comment]
Moving discussion to the main repo as this repo will be going away - https://github.com/BlueSCSI/BlueSCSI-v2/discussions/96
